[package]
name = "crypto-arb-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
petgraph = "0.8.3"
ratatui = { version = "0.30.0", features = ["serde"] }
reqwest = "0.12.28"
tokio = { version = "1", features = ["full"] }
